(declare (usual-integrations))
(load '("lib/assert" "lib/math"))

; {{{3 Problem
; Draw the tree illustrating the process generated by the count-change
; procedure of section 1.2.2 in making change for 11 cents. What are the orders
; of growth of the space and number of steps used by this process as the amount
; to be changed increases?

(define (count-change amount)
  (cc amount 5 0 amount))

(define (cc amount kinds-of-coins #!optional n orig-amount)
  (define n+ (inc n))

  (term-display (string "TEST - Orig-Amount: " orig-amount ", Amount: "  amount ", Calls: " n+))

  (cond ((= amount 0) 1)
        ((or (< amount 0)  (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1) n+ orig-amount)
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins n+ orig-amount)))))

(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))


;                    Solution      Called   Branches
;                    ========      ======   ========  
; (count-change 0) ;   1              1       0
;
; (count-change 1) ;   1             11       5
; (count-change 2) ;   1             13       6
; (count-change 3) ;   1             15       7
; (count-change 4) ;   1             17       8
; (count-change 5) ;   2             19       9
;
; (count-change 6) ;   2             25       10  
; (count-change 7) ;   2             29       11
; (count-change 8) ;   2             33       12
; (count-change 9) ;   2             37       13
; (count-change 10) ;  4             41       14
;
; (count-change 11) ;  4             55       15
; (count-change 12) ;  4             63       16
; (count-change 13) ;  4             71       17
; (count-change 14) ;  4             79       18
; (count-change 15) ;  6             87       19
;
; (count-change 16) ;  6             103      20
; (count-change 17) ;  6             115      21
; (count-change 18) ;  6             127      22
; (count-change 19) ;  6             139      23
; (count-change 20) ;  9             151      24
;
; (count-change 21) ;  9             177      25
;
; (count-change 24) ;  9             231      28
; (count-change 25) ;  13            249      29
; (count-change 30) ;  18            391      34
; 
; (count-change 35) ;  24            583      39
; (count-change 40) ;  31            
; (count-change 45) ;  39            
; (count-change 50) ;  50            
; (count-change 55) ;  62            
; (count-change 60) ;  77            
; (count-change 65) ;  93            
; (count-change 70) ;  112           
; (count-change 75) ;  134           
; (count-change 80) ;  159           
; (count-change 85) ;  187           
; (count-change 90) ;  218           
; (count-change 95) ;  252           
; (count-change 100);  292          15499     100 
